### ISSUE TITLE
Error analyzing sample images

### ISSUE THREAD

**Issue by aereimer** [ucsb-goard-lab/EstrousNet#2]
Hi there, 

I'm having an issue when trying to evaluate the sample images (see below). A new folder is created (photos are converted to BW) but the app stops with the status message: "Preprocessing images..."

`Select your folder of test images: 
Unrecognized field name "Layers".

Error in EstrousNetClassifier/prepareImageDatastore (line 219)
            inputSize = obj.trainedNet.Layers(1).InputSize;

Error in EstrousNetGUI/RUNESTROUSNETButtonPushed (line 148)
            aug_test_imds = app.classifier.prepareImageDatastore();

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 138)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(appdesigner.internal.service.AppManagementService.instance(),app,callback,requiresEventData,event) (line 63)
            newCallback = @(source, event)executeCallback(appdesigner.internal.service.AppManagementService.instance(), ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.`

**Comment by asiadofat** [comment]
Hello :) I am having the same issue, but mine stops on "Generating cyclicity predictions...". Not sure why. It works fine with the test images but not with the ones I try to upload. I thought it was taking a long time because the files were large, but they are smaller than the sample images.

**Comment by NoraWolcott** [comment]
Hi Adriano, thanks for bringing this up! The code is failing to recognize the field "layers" of the pretrained network due to a technicality in GitHub's large file storage system, in which the file will not download correctly unless it is done over command line. Alternatively, you can navigate to the file in GitHub desktop and download the full 84MB version there.

I've moved the file to the main folder and renamed it "PretrainedNet.mat" to clarify which file I'm referring to, and updated the README with this info (also updated the code to be compatible with the new filename, etc.). Hope this helps!

**Comment by aereimer** [comment]
Hey Nora, thanks! I downloaded the file manually and it is working now.
Thank you once again!
