### ISSUE TITLE
image quality is too low to classify stages

### ISSUE THREAD

**Issue by nazdundar** [ucsb-goard-lab/EstrousNet#3]
Hi,

I would like to start using EstrousNet but have been running into image processing issues. My raw images are in the nd2 format and when I convert them to jpeg or png using imageJ I lose a lot of resolution and the program cannot interpret the images correctly. I'm attaching what the jpeg image looks like when I open it on the computer and when I open it with the gui. Any suggestions on how to convert images for them to have enough resolution for the software to work correctly?

Thanks!

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/40470122/217360396-0e2e8fe0-88ac-4a
![230102_AM_F1](https://user-images.githubusercontent.com/40470122/217360518-74d6cfa9-13a7-4058-bd23-8ed19e025469.jpg)
c7-a816-752b4c683203.png">

**Comment by NoraWolcott** [comment]
Hi,

Sorry for the delayed reply! I don't usually work with Nikon images, but my recent additions to the net may solve your problem. The classification pipeline is now compatible with TIF and TIFF files, so if you're able to convert the nd2 images to either of those formats in ImageJ that should preserve the image quality and work in the EstrousNet GUI. I also modified the plotting GUI so that the quality of smaller images are preserved. Please note that though smaller images are now displayed with better quality, low resolution may affect the classification accuracy of the net. Hope that helps!

Best,
Nora
